POST http://localhost:3000/zombies/ HTTP/1.1
content-type: application/json

{
    "zombieName": "Zombie1",
    "creationDate": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

PATCH http://localhost:3000/zombies/7 HTTP/1.1
content-type: application/json

{
    "zombieName": "Zombie2"
}

###

DELETE http://localhost:3000/zombies/7 HTTP/1.1
